stages:
  - build
  - test
  - docker

variables:
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:latest

default:
  image: maven:3.8.8-openjdk-17

build:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS test

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - master

