name: CI/CD

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Dar permisos de ejecución a mvnw
        run: chmod +x ./mvnw
      - name: Copiar settings.xml
        run: cp settings.xml $HOME/settings.xml

      - name: Reemplazar credenciales en settings.xml
        run: |
          sed -i "s|\${ARTIFACT_USERNAME}|${{ secrets.ARTIFACT_USERNAME }}|g" $HOME/settings.xml
          sed -i "s|\${ARTIFACT_TOKEN}|${{ secrets.ARTIFACT_TOKEN }}|g" $HOME/settings.xml
        shell: bash
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests -s $HOME/settings.xml
      - name: Run tests
        run: ./mvnw test

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 8080:8080 ghcr.io/${{ github.repository }}:latest
